server:
  port: 8600

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/notification_db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info

app:
  security:
    jwt:
      secret: ${JWT_SECRET:change-me-change-me-change-me-change-me}

reservation:
  events:
    exchange: reservation.events

notification:
  reservation-events:
    queue: notification.reservation-events

identity-service:
  url: http://localhost:8100

workshop-service:
  url: http://localhost:8200

resilience4j:
  circuitbreaker:
    instances:
      externalNotificationProvider:
        sliding-window-size: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
