server:
  port: 8200

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/workshop_db
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka/}

identity-service:
  url: ${IDENTITY_SERVICE_URL:http://localhost:8100}

reservation-service:
  url: ${RESERVATION_SERVICE_URL:http://localhost:8300}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
